# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sircu/ECE385/final/final.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/mb_block_hdmi_text_controller_0_1.xci
# IP: The module: 'mb_block_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/hdmi_tx_0_3/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/sircu/ECE385/final/final.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/mb_block_hdmi_text_controller_0_1.xci
# IP: The module: 'mb_block_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/hdmi_tx_0_3/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sircu/ECE385/final/final.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc
