# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lukej/ECE_385/Final_Project/final/final.srcs/sources_1/bd/mb_block/ip/mb_block_lmb_bram_3/mb_block_lmb_bram_3.xci
# IP: The module: 'mb_block_lmb_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukej/ECE_385/Final_Project/final/final.gen/sources_1/bd/mb_block/ip/mb_block_lmb_bram_3/mb_block_lmb_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_lmb_bram_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/lukej/ECE_385/Final_Project/final/final.srcs/sources_1/bd/mb_block/ip/mb_block_lmb_bram_3/mb_block_lmb_bram_3.xci
# IP: The module: 'mb_block_lmb_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukej/ECE_385/Final_Project/final/final.gen/sources_1/bd/mb_block/ip/mb_block_lmb_bram_3/mb_block_lmb_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_lmb_bram_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
